version: '1.0.0.{build}'

branches:
  except:
    - gh-pages

cache:
  - mt-1090.zip

install:
  - ps: if (-not (Test-Path "$pwd\mt-1090.zip")) { (New-Object Net.WebClient).DownloadFile("https://s3.amazonaws.com/mqllab/terminal/mt4-1090.zip", "$pwd\mt-1090.zip") }
  - 7z x mt-1090.zip

build_script:
  - echo "Compiling MQLUNITTest.mq4..."
  - compile.cmd MQL4\Scripts\MQLUNIT\Tests\MQLUNITTest

test_script:
  - test.cmd
  - dir MQL4\Files\MQLUNIT
  - ps: if (-not (Test-Path "$pwd\MQL4\Files\MQLUNIT\SUCCESS")) { exit -1 }

on_finish:
  - echo https://ci.appveyor.com/api/testresults/junit/%APPVEYOR_JOB_ID%
  - curl -i -X POST -H "Content-Type: multipart/form-data" -F "data=@MQL4\Files\MQLUNIT\MQLUNITTest.xml" https://ci.appveyor.com/api/testresults/junit/%APPVEYOR_JOB_ID%
#  - ps: (New-Object Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", "$pwd\MQL4\Files\MQLUNIT\MQLUNITTest.xml")
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
