version: '1.0.0.{build}'

branches:
  except:
    - gh-pages

#environment:

cache:
  - mt-1090.zip

install:
  - ps: if (-not (Test-Path "$pwd\mt-1090.zip")) { (New-Object Net.WebClient).DownloadFile("https://s3.amazonaws.com/mqllab/terminal/mt4-1090.zip", "$pwd\mt-1090.zip") }
  - 7z x mt-1090.zip

build_script:
  - echo "Compiling MQLUNITTest.mq4..."
  - compile.cmd MQL4\Scripts\MQLUNIT\Tests\MQLUNITTest

test_script:
  - test.cmd
  - dir MQL4\Files\MQLUNIT
  - ps: if (-not (Test-Path "$pwd\MQL4\Files\MQLUNIT\SUCCESS")) { exit -1 }

#after_test:
#  - doxygen.exe --version
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
