#sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - doxygen docs/Doxyfile

#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: $TRAVIS_BUILD_DIR/docs/html
#  github_token: $GITHUB_API_KEY
#  on:
#    branch: master
#
